[package]
name = "foc-controller"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "foc-controller"
path = "src/main.rs"

[dependencies]
torc-core = { workspace = true }
torc-trc = { workspace = true }
