[package]
name = "torc-targets"
description = "Target platform model definitions and parsing for the Torc language"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
toml = "0.8"
